# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('password', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='OtherAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=264)),
                ('username', models.CharField(max_length=264)),
                ('password', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('library_card_number', models.CharField(max_length=13, unique=True)),
                ('phone_number', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='YahooAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=264)),
                ('password', models.CharField(max_length=264)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron_password_app.Patron')),
            ],
        ),
        migrations.AddField(
            model_name='otheraccount',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron_password_app.Patron'),
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='patron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron_password_app.Patron'),
        ),
    ]
