# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patron_password_app', '0002_hotmailaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hotmailaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='otheraccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='yahooaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='googleaccount',
            name='patron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patron_password_app.Patron'),
        ),
        migrations.AlterField(
            model_name='hotmailaccount',
            name='patron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patron_password_app.Patron'),
        ),
        migrations.AlterField(
            model_name='otheraccount',
            name='patron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patron_password_app.Patron'),
        ),
        migrations.AlterField(
            model_name='yahooaccount',
            name='patron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='patron_password_app.Patron'),
        ),
    ]
