# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron_password_app', '0004_auto_20170320_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='first_name',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='patron',
            name='last_name',
            field=models.CharField(blank=True, max_length=264),
        ),
        migrations.AlterField(
            model_name='patron',
            name='library_card_number',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
