# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patron_password_app', '0005_auto_20170321_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleaccount',
            old_name='password',
            new_name='gpassword',
        ),
        migrations.RenameField(
            model_name='googleaccount',
            old_name='username',
            new_name='gusername',
        ),
    ]
