# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patron_password_app', '0006_auto_20170321_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleaccount',
            old_name='gpassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='googleaccount',
            old_name='gusername',
            new_name='username',
        ),
    ]
